# .claude/scripts/primer-reconcile.py
# Commit-time governance drift checker -- generated by /primer reconcile.
# Validates that every registry check id resolves to live config (exit 2 on
# failure) and reports live checks missing from the registry (warn only).
# Author: Pierre Grothe
# Date: 2026-07-02
"""Validate .primer/policies/registry.yaml against live enforcement config.

Blocking (exit 2): a registry check whose id does not resolve per its
kind's rule; a justifying ADR with no file (unless listed in known_gaps).
Warning (exit 0): ORPHANED-CHECK -- a live pre-commit hook id or ratchet
key that no registry policy claims.

Stdlib only. User-owned YAML is line-scanned, never YAML-parsed. The
registry is parsed with a line-oriented state machine over primer's
constrained emission format (see the skill's registry-schema.md).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

__all__ = ["main"]

REGISTRY = Path(".primer/policies/registry.yaml")
PRECOMMIT = Path(".pre-commit-config.yaml")
SETTINGS = Path(".claude/settings.json")
WORKFLOWS = Path(".github/workflows")
ADR_DIR = Path(".primer/adr")

_FLOW = re.compile(r"\[(.*?)\]")


def _flow_list(line: str) -> list[str]:
    """Parse a single-line flow list like `key: [A, B]`.

    Args:
        line: The raw registry line containing a bracketed list.

    Returns:
        The stripped list items; empty when no bracket content.
    """
    m = _FLOW.search(line)
    if not m or not m.group(1).strip():
        return []
    return [t.strip() for t in m.group(1).split(",")]


def parse_registry(text: str) -> tuple[list[dict], set[str], str]:
    """Parse the constrained registry format.

    Args:
        text: Full registry.yaml content.

    Returns:
        A (policies, known_gaps, baselines_path) tuple; each policy dict
        carries slug, status, justifying_adrs, and checks (field dicts).
    """
    policies: list[dict] = []
    gaps: set[str] = set()
    baselines = ".ratchet/baselines.json"
    pol: dict | None = None
    chk: dict | None = None
    in_checks = False
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith("known_gaps:"):
            gaps = {g.replace("ADR-", "") for g in _flow_list(line)}
        elif line.startswith("baselines:"):
            baselines = line.split(":", 1)[1].split("#")[0].strip()
        elif re.match(r"^  - slug:", line):
            slug = line.split(":", 1)[1].split("#")[0].strip()
            pol = {"slug": slug, "adrs": [], "checks": [], "status": ""}
            policies.append(pol)
            in_checks = False
        elif pol is not None and re.match(r"^    justifying_adrs:", line):
            pol["adrs"] = _flow_list(line)
        elif pol is not None and re.match(r"^    checks:", line):
            in_checks = True
        elif pol is not None and re.match(r"^    status:", line):
            pol["status"] = line.split(":", 1)[1].split("#")[0].strip()
            in_checks = False
        elif in_checks and re.match(r"^      - kind:", line):
            chk = {"kind": line.split(":", 1)[1].split("#")[0].strip()}
            pol["checks"].append(chk)
        elif in_checks and chk is not None and re.match(r"^        \w", line):
            key, _, val = line.strip().partition(":")
            chk[key] = val.split("#")[0].strip()
    return policies, gaps, baselines


def live_precommit_ids() -> set[str]:
    """Collect every hook id declared in .pre-commit-config.yaml.

    Returns:
        The set of `- id:` values; empty when the file is absent.
    """
    if not PRECOMMIT.is_file():
        return set()
    text = PRECOMMIT.read_text(encoding="utf-8", errors="replace")
    return set(re.findall(r"^\s*-\s*id:\s*(\S+)", text, re.M))


def _collect_keys(obj: object) -> set[str]:
    """Collect dict keys recursively at every nesting depth.

    Args:
        obj: Any JSON-decoded value.

    Returns:
        Every dict key found in obj, at any depth, as strings.
    """
    keys: set[str] = set()
    if isinstance(obj, dict):
        for key, value in obj.items():
            keys.add(str(key))
            keys.update(_collect_keys(value))
    return keys


_ratchet_key_cache: dict[str, set[str]] = {}


def live_ratchet_keys(baseline_path: str) -> set[str]:
    """Collect ratchet baseline keys at any nesting depth, cached per path.

    Args:
        baseline_path: Project-root-relative path to the baseline JSON file.

    Returns:
        Every dict key found in the decoded JSON, at any depth; empty when
        the file is missing or fails to decode. Each distinct absolute
        path is loaded from disk at most once per process.
    """
    path = Path(baseline_path)
    cache_key = str(path.resolve())
    if cache_key in _ratchet_key_cache:
        return _ratchet_key_cache[cache_key]
    keys: set[str] = set()
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            data = None
        if data is not None:
            keys = _collect_keys(data)
    _ratchet_key_cache[cache_key] = keys
    return keys


def settings_commands() -> str:
    """Concatenate every hook command string in .claude/settings.json.

    Returns:
        All command strings joined by newlines; empty when absent.
    """
    if not SETTINGS.is_file():
        return ""
    data = json.loads(SETTINGS.read_text(encoding="utf-8"))
    out: list[str] = []
    for entries in data.get("hooks", {}).values():
        for entry in entries:
            for hook in entry.get("hooks", []):
                out.append(hook.get("command", ""))
    return "\n".join(out)


def resolve(chk: dict, pc_ids: set[str], ratchets: set[str],
            commands: str) -> bool:
    """Apply the per-kind resolution rule for one registry check.

    Args:
        chk: Parsed check fields (kind, id, optional bundled_into,
            optional baseline_path).
        pc_ids: Live pre-commit hook ids.
        ratchets: Live ratchet baseline keys from the default source
            (registry `baselines:` override or .ratchet/baselines.json).
        commands: Concatenated cc-hook command strings.

    Returns:
        True when the check resolves to live config.
    """
    kind, cid = chk.get("kind", ""), chk.get("id", "")
    if not cid:
        return False
    if kind == "pre-commit-hook":
        return cid in pc_ids or chk.get("bundled_into", "") in pc_ids
    if kind == "cc-hook":
        return cid in commands
    if kind == "ci-job":
        fname, _, job = cid.partition(":")
        wf = WORKFLOWS / fname
        if not (job and wf.is_file()):
            return False
        return re.search(rf"^\s+{re.escape(job)}:\s*$",
                         wf.read_text(encoding="utf-8"), re.M) is not None
    if kind == "ratchet":
        override = chk.get("baseline_path")
        keys = live_ratchet_keys(override) if override else ratchets
        return cid in keys
    if kind == "import-contract":
        if Path(cid).is_file():
            return True
        cfg = Path(".importlinter")
        return cfg.is_file() and cid in cfg.read_text(
            encoding="utf-8", errors="replace")
    if kind == "agent-rule":
        return Path(cid).is_file()
    return False


def main() -> int:
    """Run the drift check and print findings.

    Returns:
        0 when clean (orphans warn only), 2 on blocking drift.
    """
    if not REGISTRY.is_file():
        return 0  # no registry -> nothing to enforce yet
    policies, gaps, baselines = parse_registry(
        REGISTRY.read_text(encoding="utf-8", errors="replace"))
    pc_ids = live_precommit_ids()
    ratchets = live_ratchet_keys(baselines)
    commands = settings_commands()
    blocking: list[str] = []
    claimed: set[str] = set()
    for pol in policies:
        if pol["status"] == "retired":
            continue
        for adr in pol["adrs"]:
            num = adr.replace("ADR-", "")
            if num in gaps:
                continue
            if not list(ADR_DIR.glob(f"ADR-{num}*.md")):
                blocking.append(
                    f"{pol['slug']}: {adr} has no file in .primer/adr/")
        for chk in pol["checks"]:
            claimed.add(chk.get("id", ""))
            claimed.add(chk.get("bundled_into", ""))
            if not resolve(chk, pc_ids, ratchets, commands):
                blocking.append(
                    f"{pol['slug']}: {chk.get('kind')} '{chk.get('id')}' "
                    "does not resolve to live config (STALE)")
    orphans = sorted((pc_ids | ratchets) - claimed)
    for orphan in orphans:
        print(f"ORPHANED-CHECK (warn): '{orphan}' is live but claimed by "
              "no registry policy -- register it via /primer reconcile")
    if blocking:
        print("PRIMER-RECONCILE: governance drift -- fix before commit "
              "(run /primer reconcile):", file=sys.stderr)
        for item in blocking:
            print(f"  {item}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
