# .claude/scripts/primer-reconcile.py
# Commit-time governance drift checker -- generated by /primer reconcile.
# Author: Pierre Grothe
# Date: 2026-07-02
"""Validate .primer/policies/registry.yaml against live enforcement config.

Blocking (exit 2): a registry check whose id does not resolve per its
kind's rule; a justifying ADR with no file (unless listed in known_gaps).
Warning (exit 0): ORPHANED-CHECK -- a live pre-commit hook id or ratchet
key that no registry policy claims.

Stdlib only. User-owned YAML is line-scanned, never YAML-parsed. The
registry is parsed with a line-oriented state machine over primer's
constrained emission format (see the skill's registry-schema.md).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

__all__ = ["main"]

REGISTRY = Path(".primer/policies/registry.yaml")
PRECOMMIT = Path(".pre-commit-config.yaml")
SETTINGS = Path(".claude/settings.json")
WORKFLOWS = Path(".github/workflows")
ADR_DIR = Path(".primer/adr")

_FLOW = re.compile(r"\[(.*?)\]")


def _flow_list(line: str) -> list[str]:
    """Parse a list value from a registry line.

    Handles both the emitted flow-list form (`key: [A, B]`) and a
    hand-authored bare scalar/CSV (`key: A` or `key: A, B`), so a
    non-bracketed value is never silently read as an empty list.

    Args:
        line: The raw registry line containing the list value.

    Returns:
        The stripped list items; empty only when the value is truly empty.
    """
    # Strip a trailing `#` comment first (as every other field parser here
    # does), so a bracket pair inside a comment -- e.g.
    # `justifying_adrs: ADR-9  # see [ADR-3]` -- cannot hijack the value.
    line = line.split("#")[0]
    m = _FLOW.search(line)
    if m:
        inner = m.group(1).strip()
        return [t.strip().strip("'\"") for t in inner.split(",")] if inner else []
    _, _, val = line.partition(":")
    val = val.strip()
    return [t.strip().strip("'\"") for t in val.split(",") if t.strip()] if val else []


def _scalar(raw_value: str) -> str:
    """Return a registry scalar value: comment/whitespace/quote stripped.

    Args:
        raw_value: The text after a ``key:`` (may carry a trailing comment
            and/or wrapping quotes, as a YAML formatter may emit).

    Returns:
        The value with a trailing ``#`` comment, surrounding whitespace, and
        one wrapping single/double-quote pair removed -- so a quoted
        ``kind: "pre-commit-hook"`` resolves the same as the bare form.
    """
    value = raw_value.split("#")[0].strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        value = value[1:-1]
    return value


def _ci_job_present(wf: Path, job: str) -> bool:
    """Return True when job is a key under the workflow's top-level jobs map.

    Args:
        wf: Path to the GitHub Actions workflow file.
        job: The job key to look for.

    Returns:
        True when `<job>:` appears as a child key of the top-level `jobs:`
        mapping -- not merely anywhere in the file (e.g. a same-named key
        under the `on:` trigger block does not count).
    """
    lines = wf.read_text(encoding="utf-8-sig", errors="replace").splitlines()
    n = len(lines)
    idx = 0
    while idx < n:
        # Find each top-level block-style `jobs:` header (flow-style
        # `jobs: {..}` is non-idiomatic and not parsed). A file may carry
        # more than one such block (duplicate top-level keys are invalid
        # YAML but do occur); scan every block and match in any of them so
        # a real job is never wrongly reported STALE.
        if not re.match(r"^jobs:[ \t]*($|#)", lines[idx]):
            idx += 1
            continue
        idx += 1  # advance past the `jobs:` header
        job_indent = None
        while idx < n:
            line = lines[idx]
            stripped = line.strip()
            if stripped == "" or stripped.startswith("#"):
                idx += 1
                continue
            indent = len(line) - len(line.lstrip(" \t"))
            if indent == 0:
                break  # dedented; re-examine this line as a possible header
            # Job keys are the shallowest-indent direct children of jobs:.
            if job_indent is None or indent < job_indent:
                job_indent = indent
            # Allow a single- or double-quoted job key (`"build":`), a valid
            # YAML style a formatter may emit or a numeric-like name requires.
            if indent == job_indent and re.match(
                    rf"^(['\"]?){re.escape(job)}\1:(?:\s|$)", stripped):
                return True
            idx += 1
    return False


def _token_present(token: str, text: str) -> bool:
    """Return True when token appears as a discrete token, not a substring.

    Args:
        token: The identifier to look for.
        text: The text to search.

    Returns:
        True when token starts at a boundary (not preceded by a word or
        hyphen character, so `test` does not match `pytest`/`latest`/
        `attestation`) and is not immediately followed by a word character.
        A following hyphen or dot IS allowed, so a versioned/suffixed live
        name resolves (id `ruff-check` matches `ruff-check-v2.py` and
        `ruff-check.py`) while `ruff-checker` still does not.
    """
    if not token:
        return False
    return re.search(rf"(?<![\w-]){re.escape(token)}(?![\w])", text) is not None


def parse_registry(text: str) -> tuple[list[dict], set[str], str]:
    """Parse the constrained registry format.

    Args:
        text: Full registry.yaml content.

    Returns:
        A (policies, known_gaps, baselines_path) tuple; each policy dict
        carries slug, status, justifying_adrs, and checks (field dicts).
    """
    policies: list[dict] = []
    gaps: set[str] = set()
    baselines = ".ratchet/baselines.json"
    pol: dict | None = None
    chk: dict | None = None
    in_checks = False
    for raw in text.splitlines():
        line = raw.rstrip()
        if line.startswith("known_gaps:"):
            gaps = {g.replace("ADR-", "") for g in _flow_list(line)}
        elif line.startswith("baselines:"):
            baselines = _scalar(line.split(":", 1)[1])
        elif re.match(r"^  - slug:", line):
            slug = _scalar(line.split(":", 1)[1])
            pol = {"slug": slug, "adrs": [], "checks": [], "status": ""}
            policies.append(pol)
            in_checks = False
        elif pol is not None and re.match(r"^    justifying_adrs:", line):
            pol["adrs"] = _flow_list(line)
        elif pol is not None and re.match(r"^    checks:", line):
            in_checks = True
        elif pol is not None and re.match(r"^    status:", line):
            pol["status"] = _scalar(line.split(":", 1)[1])
            in_checks = False
        elif in_checks and re.match(r"^      - kind:", line):
            chk = {"kind": _scalar(line.split(":", 1)[1])}
            pol["checks"].append(chk)
        elif in_checks and chk is not None and re.match(r"^        \w", line):
            key, _, val = line.strip().partition(":")
            chk[key] = _scalar(val)
    return policies, gaps, baselines


def live_precommit_ids() -> set[str]:
    """Collect every hook id declared in .pre-commit-config.yaml.

    Returns:
        The set of `- id:` values; empty when the file is absent.
    """
    if not PRECOMMIT.is_file():
        return set()
    text = PRECOMMIT.read_text(encoding="utf-8-sig", errors="replace")
    return {mid.strip("'\"")
            for mid in re.findall(r"^\s*-\s*id:\s*(\S+)", text, re.M)}


def _collect_keys(obj: object) -> set[str]:
    """Collect dict keys recursively at every nesting depth.

    Args:
        obj: Any JSON-decoded value.

    Returns:
        Every dict key found in obj, at any depth, as strings.
    """
    keys: set[str] = set()
    if isinstance(obj, dict):
        for key, value in obj.items():
            keys.add(str(key))
            keys.update(_collect_keys(value))
    elif isinstance(obj, list):
        for item in obj:
            keys.update(_collect_keys(item))
    return keys


_ratchet_key_cache: dict[str, set[str]] = {}


def live_ratchet_keys(baseline_path: str) -> set[str]:
    """Collect ratchet baseline keys at any nesting depth, cached per path.

    Args:
        baseline_path: Project-root-relative path to the baseline JSON file.

    Returns:
        Every dict key found in the decoded JSON, at any depth; empty when
        the file is missing or fails to decode. Each distinct absolute
        path is loaded from disk at most once per process.
    """
    path = Path(baseline_path)
    cache_key = str(path.resolve())
    if cache_key in _ratchet_key_cache:
        return _ratchet_key_cache[cache_key]
    keys: set[str] = set()
    if path.is_file():
        try:
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except (json.JSONDecodeError, UnicodeDecodeError, OSError):
            data = None
        if data is not None:
            keys = _collect_keys(data)
    _ratchet_key_cache[cache_key] = keys
    return keys


def settings_commands() -> str:
    """Concatenate every hook command string in .claude/settings.json.

    Returns:
        All command strings joined by newlines; empty when absent.
    """
    if not SETTINGS.is_file():
        return ""
    try:
        data = json.loads(SETTINGS.read_text(encoding="utf-8-sig"))
    except (json.JSONDecodeError, UnicodeDecodeError, OSError):
        return ""
    out: list[str] = []
    # Tolerate any malformed shape (hooks null, a list, non-dict entries):
    # degrade to no commands rather than crash the whole governance check.
    hooks = data.get("hooks") if isinstance(data, dict) else None
    if not isinstance(hooks, dict):
        return ""
    for entries in hooks.values():
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            inner = entry.get("hooks")
            if not isinstance(inner, list):
                continue  # explicit null / non-list -> no commands, no crash
            for hook in inner:
                if isinstance(hook, dict):
                    out.append(hook.get("command", ""))
    return "\n".join(out)


def resolve(chk: dict, pc_ids: set[str], ratchets: set[str],
            commands: str) -> bool:
    """Apply the per-kind resolution rule for one registry check.

    Args:
        chk: Parsed check fields (kind, id, optional bundled_into,
            optional baseline_path).
        pc_ids: Live pre-commit hook ids.
        ratchets: Live ratchet baseline keys from the default source
            (registry `baselines:` override or .ratchet/baselines.json).
        commands: Concatenated cc-hook command strings.

    Returns:
        True when the check resolves to live config.
    """
    kind, cid = chk.get("kind", ""), chk.get("id", "")
    if not cid:
        return False
    if kind == "pre-commit-hook":
        return cid in pc_ids or chk.get("bundled_into", "") in pc_ids
    if kind == "cc-hook":
        return _token_present(cid, commands)
    if kind == "ci-job":
        fname, _, job = cid.partition(":")
        wf = WORKFLOWS / fname
        if not (job and wf.is_file()):
            return False
        return _ci_job_present(wf, job)
    if kind == "ratchet":
        override = chk.get("baseline_path")
        keys = live_ratchet_keys(override) if override else ratchets
        return cid in keys
    if kind == "import-contract":
        if Path(cid).is_file():
            return True
        cfg = Path(".importlinter")
        return cfg.is_file() and _token_present(
            cid, cfg.read_text(encoding="utf-8-sig", errors="replace"))
    if kind == "agent-rule":
        return Path(cid).is_file()
    return False


def main() -> int:
    """Run the drift check and print findings.

    Returns:
        0 when clean (orphans warn only), 2 on blocking drift.
    """
    if not REGISTRY.is_file():
        return 0  # no registry -> nothing to enforce yet
    _ratchet_key_cache.clear()  # fresh disk reads per run (in-process safe)
    policies, gaps, baselines = parse_registry(
        REGISTRY.read_text(encoding="utf-8-sig", errors="replace"))
    pc_ids = live_precommit_ids()
    ratchets = live_ratchet_keys(baselines)
    commands = settings_commands()
    blocking: list[str] = []
    claimed_pc: set[str] = set()
    claimed_ratchet: set[str] = set()
    for pol in policies:
        retired = pol["status"] == "retired"
        # A retired policy still legitimately claims its live checks, so
        # populate the claimed sets from it too -- only its blocking
        # validation is skipped (else its ids would be reported ORPHANED-CHECK).
        for chk in pol["checks"]:
            # Claim into the SAME namespace the orphan scan searches, keyed by
            # kind: a live pre-commit hook id is only "claimed" by a
            # pre-commit-hook check (directly or via bundled_into); a
            # default-baseline ratchet key only by a ratchet check reading that
            # same default baseline. A flat, kind-agnostic claimed set would let
            # an incidental cross-kind id-string collision (a ratchet key equal
            # to a live hook id) mask a genuine orphan.
            kind, cid = chk.get("kind", ""), chk.get("id", "")
            if kind == "pre-commit-hook":
                claimed_pc.add(cid)
                claimed_pc.add(chk.get("bundled_into", ""))
            elif kind == "ratchet" and chk.get("baseline_path", baselines) == baselines:
                claimed_ratchet.add(cid)
            if not retired and not resolve(chk, pc_ids, ratchets, commands):
                blocking.append(
                    f"{pol['slug']}: {chk.get('kind')} '{chk.get('id')}' "
                    "does not resolve to live config (STALE)")
        if retired:
            continue
        for adr in pol["adrs"]:
            num = adr.replace("ADR-", "")
            if num in gaps:
                continue
            if not (any(ADR_DIR.glob(f"ADR-{num}.md"))
                    or any(ADR_DIR.glob(f"ADR-{num}-*.md"))):
                blocking.append(
                    f"{pol['slug']}: {adr} has no file in .primer/adr/")
    # The orphan scan uses ONLY the default baseline, NOT per-check
    # `baseline_path` override baselines: those are large project DATA
    # (coverage, file-size -- e.g. 131 nested per-module keys plus metadata),
    # not a per-key governance surface. The check that references an override
    # already claims its key; collecting the override's other keys would flood
    # warn-only ORPHANED-CHECK noise on every commit (seen on nexus-sn: 136
    # false orphans). Override baselines are still read for resolve().
    orphans = sorted((pc_ids - claimed_pc) | (ratchets - claimed_ratchet))
    for orphan in orphans:
        print(f"ORPHANED-CHECK (warn): '{orphan}' is live but claimed by "
              "no registry policy -- register it via /primer reconcile")
    if blocking:
        print("PRIMER-RECONCILE: governance drift -- fix before commit "
              "(run /primer reconcile):", file=sys.stderr)
        for item in blocking:
            print(f"  {item}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
